version: '3'

services:
  vault:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      PORT: "${PORT}"
      SECRET: "${SECRET}"
  redis:
    image: "redis:alpine"
